#!/usr/bin/env python3
"""
CyberArk to Secret Server Code Converter

Takes scan results from ccp_code_scanner.py and generates
Secret Server equivalent code snippets for each detected pattern.

Usage:
    python code_converter.py scan_results.json --language python --output converted/
"""

import argparse
import json
import os
from pathlib import Path
from typing import Dict, List

# ============================================
# CODE TEMPLATES BY LANGUAGE
# ============================================

TEMPLATES = {
    "python": {
        "header": '''#!/usr/bin/env python3
"""
Secret Server Integration
Converted from CyberArk CCP
Generated by PAM Migration Assistant
"""

import requests
from typing import Optional
from functools import lru_cache
import time

class SecretServerClient:
    """Client for retrieving secrets from Delinea Secret Server."""
    
    def __init__(self, base_url: str, client_id: str, client_secret: str):
        self.base_url = base_url.rstrip('/')
        self.client_id = client_id
        self.client_secret = client_secret
        self._token = None
        self._token_expiry = 0
    
    def _get_token(self) -> str:
        """Get OAuth2 access token, refreshing if needed."""
        if self._token and time.time() < self._token_expiry - 60:
            return self._token
        
        response = requests.post(
            f"{self.base_url}/oauth2/token",
            data={
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret
            }
        )
        response.raise_for_status()
        data = response.json()
        
        self._token = data["access_token"]
        self._token_expiry = time.time() + data.get("expires_in", 3600)
        return self._token
    
    def _headers(self) -> dict:
        """Get authorization headers."""
        return {"Authorization": f"Bearer {self._get_token()}"}
    
    def get_secret(self, secret_id: int) -> dict:
        """Retrieve a secret by ID."""
        response = requests.get(
            f"{self.base_url}/api/v1/secrets/{secret_id}",
            headers=self._headers()
        )
        response.raise_for_status()
        return response.json()
    
    def get_password(self, secret_id: int) -> str:
        """Retrieve just the password field from a secret."""
        response = requests.get(
            f"{self.base_url}/api/v1/secrets/{secret_id}/fields/password",
            headers=self._headers()
        )
        response.raise_for_status()
        return response.json()["value"]
    
    def search_secrets(self, search_text: str, folder_id: Optional[int] = None) -> List[dict]:
        """Search for secrets by text."""
        params = {"filter.searchText": search_text}
        if folder_id:
            params["filter.folderId"] = folder_id
        
        response = requests.get(
            f"{self.base_url}/api/v1/secrets",
            headers=self._headers(),
            params=params
        )
        response.raise_for_status()
        return response.json()["records"]


# Initialize client (configure via environment variables)
import os
ss_client = SecretServerClient(
    base_url=os.environ.get("SECRET_SERVER_URL", "https://secretserver.company.com/SecretServer"),
    client_id=os.environ.get("SECRET_SERVER_CLIENT_ID"),
    client_secret=os.environ.get("SECRET_SERVER_CLIENT_SECRET")
)
''',
        "get_password": '''
def get_credential(secret_id: int) -> str:
    """
    Retrieve password from Secret Server.
    
    MIGRATION NOTE: Previously retrieved from CyberArk CCP.
    CyberArk AppID: {app_id}
    CyberArk Safe: {safe}
    CyberArk Object: {object}
    Secret Server Secret ID: {secret_id}
    """
    return ss_client.get_password(secret_id)
''',
    },
    
    "powershell": {
        "header": '''<#
.SYNOPSIS
    Secret Server Integration Module
    Converted from CyberArk CCP/psPAS
    Generated by PAM Migration Assistant

.DESCRIPTION
    Provides functions to retrieve secrets from Delinea Secret Server,
    replacing CyberArk CCP/AAM functionality.

.NOTES
    Requires: Thycotic.SecretServer PowerShell module
    Install: Install-Module -Name Thycotic.SecretServer -Scope CurrentUser
#>

# Import Secret Server module
if (-not (Get-Module -ListAvailable -Name Thycotic.SecretServer)) {
    Write-Error "Thycotic.SecretServer module not installed. Run: Install-Module -Name Thycotic.SecretServer"
    exit 1
}
Import-Module Thycotic.SecretServer

# Configuration - set via environment variables or modify here
$script:SSConfig = @{
    ServerUrl = $env:SECRET_SERVER_URL ?? "https://secretserver.company.com/SecretServer"
    ClientId = $env:SECRET_SERVER_CLIENT_ID
    ClientSecret = $env:SECRET_SERVER_CLIENT_SECRET
}

# Session management
$script:TssSession = $null

function Initialize-SecretServerSession {
    <#
    .SYNOPSIS
        Initialize connection to Secret Server
    #>
    [CmdletBinding()]
    param()
    
    if ($null -eq $script:TssSession -or -not $script:TssSession.IsValidToken()) {
        $secureSecret = ConvertTo-SecureString $script:SSConfig.ClientSecret -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential($script:SSConfig.ClientId, $secureSecret)
        
        $script:TssSession = New-TssSession -SecretServer $script:SSConfig.ServerUrl -Credential $cred
    }
    
    return $script:TssSession
}

function Get-SecretServerPassword {
    <#
    .SYNOPSIS
        Retrieve password from Secret Server
    
    .PARAMETER SecretId
        The Secret Server secret ID
    
    .EXAMPLE
        $password = Get-SecretServerPassword -SecretId 1234
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [int]$SecretId
    )
    
    $session = Initialize-SecretServerSession
    $secret = Get-TssSecret -TssSession $session -Id $SecretId
    
    # Return password field
    return $secret.GetFieldValue("password")
}

function Get-SecretServerCredential {
    <#
    .SYNOPSIS
        Retrieve full credential (username + password) from Secret Server
    
    .PARAMETER SecretId
        The Secret Server secret ID
    
    .EXAMPLE
        $cred = Get-SecretServerCredential -SecretId 1234
        Connect-Server -Credential $cred
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [int]$SecretId
    )
    
    $session = Initialize-SecretServerSession
    $secret = Get-TssSecret -TssSession $session -Id $SecretId
    
    $username = $secret.GetFieldValue("username")
    $password = $secret.GetFieldValue("password") | ConvertTo-SecureString -AsPlainText -Force
    
    return New-Object System.Management.Automation.PSCredential($username, $password)
}
''',
        "get_password": '''
# MIGRATION NOTE: 
# Previously: Get-PASAccountPassword -AccountID "{account_id}" from Safe "{safe}"
# Now: Get-SecretServerPassword -SecretId {secret_id}
''',
    },
    
    "csharp": {
        "header": '''/*
 * Secret Server Integration
 * Converted from CyberArk CCP/.NET SDK
 * Generated by PAM Migration Assistant
 * 
 * NuGet Package Required: Thycotic.SecretServer.SDK
 */

using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Threading.Tasks;

namespace SecretServerIntegration
{
    public class SecretServerClient : IDisposable
    {
        private readonly HttpClient _httpClient;
        private readonly string _baseUrl;
        private readonly string _clientId;
        private readonly string _clientSecret;
        private string _accessToken;
        private DateTime _tokenExpiry;

        public SecretServerClient(string baseUrl, string clientId, string clientSecret)
        {
            _baseUrl = baseUrl.TrimEnd('/');
            _clientId = clientId;
            _clientSecret = clientSecret;
            _httpClient = new HttpClient();
        }

        private async Task<string> GetAccessTokenAsync()
        {
            if (!string.IsNullOrEmpty(_accessToken) && DateTime.UtcNow < _tokenExpiry.AddMinutes(-1))
            {
                return _accessToken;
            }

            var content = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("grant_type", "client_credentials"),
                new KeyValuePair<string, string>("client_id", _clientId),
                new KeyValuePair<string, string>("client_secret", _clientSecret)
            });

            var response = await _httpClient.PostAsync($"{_baseUrl}/oauth2/token", content);
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var tokenResponse = JsonSerializer.Deserialize<TokenResponse>(json);

            _accessToken = tokenResponse.AccessToken;
            _tokenExpiry = DateTime.UtcNow.AddSeconds(tokenResponse.ExpiresIn);

            return _accessToken;
        }

        public async Task<string> GetPasswordAsync(int secretId)
        {
            var token = await GetAccessTokenAsync();
            _httpClient.DefaultRequestHeaders.Authorization = 
                new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.GetAsync(
                $"{_baseUrl}/api/v1/secrets/{secretId}/fields/password");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var fieldResponse = JsonSerializer.Deserialize<FieldResponse>(json);

            return fieldResponse.Value;
        }

        public async Task<SecretModel> GetSecretAsync(int secretId)
        {
            var token = await GetAccessTokenAsync();
            _httpClient.DefaultRequestHeaders.Authorization = 
                new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.GetAsync($"{_baseUrl}/api/v1/secrets/{secretId}");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            return JsonSerializer.Deserialize<SecretModel>(json);
        }

        public void Dispose()
        {
            _httpClient?.Dispose();
        }

        private class TokenResponse
        {
            public string AccessToken { get; set; }
            public int ExpiresIn { get; set; }
        }

        private class FieldResponse
        {
            public string Value { get; set; }
        }
    }

    public class SecretModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int FolderId { get; set; }
        public SecretItem[] Items { get; set; }
    }

    public class SecretItem
    {
        public string FieldName { get; set; }
        public string ItemValue { get; set; }
    }
}

/*
 * Usage Example:
 * 
 * var client = new SecretServerClient(
 *     Environment.GetEnvironmentVariable("SECRET_SERVER_URL"),
 *     Environment.GetEnvironmentVariable("SECRET_SERVER_CLIENT_ID"),
 *     Environment.GetEnvironmentVariable("SECRET_SERVER_CLIENT_SECRET")
 * );
 * 
 * string password = await client.GetPasswordAsync(secretId);
 */
''',
        "get_password": '''
// MIGRATION NOTE:
// Previously: CyberArk PasswordSDK.GetPassword(appId, safe, object)
// Now: await ssClient.GetPasswordAsync({secret_id})
''',
    },
    
    "java": {
        "header": '''/*
 * Secret Server Integration
 * Converted from CyberArk Java SDK
 * Generated by PAM Migration Assistant
 */

package com.company.secretserver;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.time.Instant;
import com.google.gson.Gson;
import com.google.gson.JsonObject;

public class SecretServerClient {
    private final String baseUrl;
    private final String clientId;
    private final String clientSecret;
    private final HttpClient httpClient;
    private final Gson gson;
    
    private String accessToken;
    private Instant tokenExpiry;

    public SecretServerClient(String baseUrl, String clientId, String clientSecret) {
        this.baseUrl = baseUrl.replaceAll("/$", "");
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(30))
            .build();
        this.gson = new Gson();
    }

    private String getAccessToken() throws Exception {
        if (accessToken != null && Instant.now().isBefore(tokenExpiry.minusSeconds(60))) {
            return accessToken;
        }

        String body = String.format(
            "grant_type=client_credentials&client_id=%s&client_secret=%s",
            clientId, clientSecret
        );

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(baseUrl + "/oauth2/token"))
            .header("Content-Type", "application/x-www-form-urlencoded")
            .POST(HttpRequest.BodyPublishers.ofString(body))
            .build();

        HttpResponse<String> response = httpClient.send(request, 
            HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Failed to get token: " + response.body());
        }

        JsonObject json = gson.fromJson(response.body(), JsonObject.class);
        accessToken = json.get("access_token").getAsString();
        int expiresIn = json.get("expires_in").getAsInt();
        tokenExpiry = Instant.now().plusSeconds(expiresIn);

        return accessToken;
    }

    public String getPassword(int secretId) throws Exception {
        String token = getAccessToken();

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(baseUrl + "/api/v1/secrets/" + secretId + "/fields/password"))
            .header("Authorization", "Bearer " + token)
            .GET()
            .build();

        HttpResponse<String> response = httpClient.send(request,
            HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Failed to get password: " + response.body());
        }

        JsonObject json = gson.fromJson(response.body(), JsonObject.class);
        return json.get("value").getAsString();
    }

    public JsonObject getSecret(int secretId) throws Exception {
        String token = getAccessToken();

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(baseUrl + "/api/v1/secrets/" + secretId))
            .header("Authorization", "Bearer " + token)
            .GET()
            .build();

        HttpResponse<String> response = httpClient.send(request,
            HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Failed to get secret: " + response.body());
        }

        return gson.fromJson(response.body(), JsonObject.class);
    }
}

/*
 * Usage:
 * 
 * SecretServerClient client = new SecretServerClient(
 *     System.getenv("SECRET_SERVER_URL"),
 *     System.getenv("SECRET_SERVER_CLIENT_ID"),
 *     System.getenv("SECRET_SERVER_CLIENT_SECRET")
 * );
 * 
 * String password = client.getPassword(secretId);
 */
''',
        "get_password": '''
// MIGRATION NOTE:
// Previously: CyberArk JavaPasswordSDK.getPassword(appId, safe, object)
// Now: ssClient.getPassword({secret_id})
''',
    },
}


def load_scan_results(input_path: str) -> dict:
    """Load scan results from JSON file."""
    with open(input_path, 'r') as f:
        return json.load(f)


def generate_conversion(matches: List[dict], language: str, output_dir: str):
    """Generate converted code files."""
    if language not in TEMPLATES:
        print(f"Error: Unsupported language '{language}'")
        print(f"Supported: {', '.join(TEMPLATES.keys())}")
        return
    
    os.makedirs(output_dir, exist_ok=True)
    
    template = TEMPLATES[language]
    
    # Generate main client file
    ext = {"python": ".py", "powershell": ".ps1", "csharp": ".cs", "java": ".java"}[language]
    client_file = os.path.join(output_dir, f"secret_server_client{ext}")
    
    with open(client_file, 'w') as f:
        f.write(template["header"])
    
    print(f"Generated: {client_file}")
    
    # Generate migration notes file
    notes_file = os.path.join(output_dir, "migration_notes.md")
    with open(notes_file, 'w') as f:
        f.write("# CyberArk to Secret Server Migration Notes\n\n")
        f.write(f"Generated from scan results\n\n")
        f.write("## Detected CyberArk Dependencies\n\n")
        
        for match in matches:
            f.write(f"### {match['file_path']}:{match['line_number']}\n\n")
            f.write(f"- **Pattern:** {match['pattern_name']}\n")
            f.write(f"- **Risk:** {match['risk_level']}\n")
            f.write(f"- **Description:** {match['description']}\n")
            f.write(f"- **Migration Action:** {match['migration_action']}\n")
            f.write(f"- **Secret Server Equivalent:** {match['secret_server_equivalent']}\n")
            f.write(f"- **Original Code:** `{match['line_content']}`\n\n")
    
    print(f"Generated: {notes_file}")
    
    # Generate mapping file template
    mapping_file = os.path.join(output_dir, "secret_mapping.json")
    mapping = {
        "description": "Map CyberArk AppID/Safe/Object to Secret Server Secret IDs",
        "mappings": []
    }
    
    # Extract unique CyberArk references from matches
    seen = set()
    for match in matches:
        if match['pattern_name'] in ['CCP_APPID', 'CCP_SAFE_REFERENCE', 'CCP_OBJECT_REFERENCE']:
            key = match['line_content']
            if key not in seen:
                seen.add(key)
                mapping["mappings"].append({
                    "cyberark_reference": match['line_content'],
                    "file": match['file_path'],
                    "secret_server_secret_id": "TODO: Fill in Secret ID after migration",
                    "notes": ""
                })
    
    with open(mapping_file, 'w') as f:
        json.dump(mapping, f, indent=2)
    
    print(f"Generated: {mapping_file}")
    print(f"\nTODO: Fill in secret_mapping.json with Secret Server Secret IDs")


def main():
    parser = argparse.ArgumentParser(
        description="Convert CyberArk code patterns to Secret Server equivalents"
    )
    parser.add_argument(
        "input",
        help="Path to scan results JSON file from ccp_code_scanner.py"
    )
    parser.add_argument(
        "--language", "-l",
        choices=["python", "powershell", "csharp", "java"],
        default="python",
        help="Target language for generated code (default: python)"
    )
    parser.add_argument(
        "--output", "-o",
        default="./converted",
        help="Output directory for generated files (default: ./converted)"
    )
    
    args = parser.parse_args()
    
    if not os.path.exists(args.input):
        print(f"Error: Input file not found: {args.input}")
        return 1
    
    scan_results = load_scan_results(args.input)
    matches = scan_results.get("matches", [])
    
    if not matches:
        print("No matches found in scan results.")
        return 0
    
    print(f"Processing {len(matches)} matches...")
    generate_conversion(matches, args.language, args.output)
    
    return 0


if __name__ == "__main__":
    exit(main())
