/*
 * Secret Server Integration - C#/.NET Client
 * Converted from CyberArk CCP/.NET SDK
 * Generated by PAM Migration Assistant
 *
 * NuGet Package Required: Thycotic.SecretServer.SDK (optional, this uses REST API directly)
 *
 * Usage:
 *     var client = new SecretServerClient(
 *         Environment.GetEnvironmentVariable("SECRET_SERVER_URL"),
 *         Environment.GetEnvironmentVariable("SECRET_SERVER_CLIENT_ID"),
 *         Environment.GetEnvironmentVariable("SECRET_SERVER_CLIENT_SECRET")
 *     );
 *
 *     string password = await client.GetPasswordAsync(secretId);
 */

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace SecretServerIntegration
{
    /// <summary>
    /// Client for retrieving secrets from Delinea Secret Server.
    /// Replaces CyberArk CCP .NET SDK functionality.
    /// </summary>
    public class SecretServerClient : IDisposable
    {
        private readonly HttpClient _httpClient;
        private readonly string _baseUrl;
        private readonly string _clientId;
        private readonly string _clientSecret;
        private string _accessToken;
        private DateTime _tokenExpiry;

        /// <summary>
        /// Initialize Secret Server client.
        /// </summary>
        /// <param name="baseUrl">Secret Server URL (e.g., https://secretserver.company.com/SecretServer)</param>
        /// <param name="clientId">OAuth2 client ID</param>
        /// <param name="clientSecret">OAuth2 client secret</param>
        public SecretServerClient(string baseUrl, string clientId, string clientSecret)
        {
            _baseUrl = baseUrl.TrimEnd('/');
            _clientId = clientId;
            _clientSecret = clientSecret;
            _httpClient = new HttpClient
            {
                Timeout = TimeSpan.FromSeconds(30)
            };
        }

        /// <summary>
        /// Get OAuth2 access token, refreshing if needed.
        /// </summary>
        private async Task<string> GetAccessTokenAsync()
        {
            // Return cached token if still valid
            if (!string.IsNullOrEmpty(_accessToken) && DateTime.UtcNow < _tokenExpiry.AddMinutes(-1))
            {
                return _accessToken;
            }

            var content = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("grant_type", "client_credentials"),
                new KeyValuePair<string, string>("client_id", _clientId),
                new KeyValuePair<string, string>("client_secret", _clientSecret)
            });

            var response = await _httpClient.PostAsync($"{_baseUrl}/oauth2/token", content);
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var tokenResponse = JsonSerializer.Deserialize<TokenResponse>(json);

            _accessToken = tokenResponse.AccessToken;
            _tokenExpiry = DateTime.UtcNow.AddSeconds(tokenResponse.ExpiresIn);

            return _accessToken;
        }

        /// <summary>
        /// Retrieve just the password field from a secret.
        /// </summary>
        /// <param name="secretId">The Secret Server secret ID</param>
        /// <returns>Password string</returns>
        /// <remarks>
        /// MIGRATION NOTE:
        /// CyberArk equivalent: PasswordSDK.GetPassword(appId, safe, object)
        /// </remarks>
        public async Task<string> GetPasswordAsync(int secretId)
        {
            var token = await GetAccessTokenAsync();
            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.GetAsync(
                $"{_baseUrl}/api/v1/secrets/{secretId}/fields/password");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var fieldResponse = JsonSerializer.Deserialize<FieldResponse>(json);

            return fieldResponse.Value;
        }

        /// <summary>
        /// Retrieve a specific field from a secret.
        /// </summary>
        /// <param name="secretId">The Secret Server secret ID</param>
        /// <param name="fieldSlug">Field name (e.g., 'username', 'password', 'notes')</param>
        /// <returns>Field value as string</returns>
        public async Task<string> GetFieldAsync(int secretId, string fieldSlug)
        {
            var token = await GetAccessTokenAsync();
            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.GetAsync(
                $"{_baseUrl}/api/v1/secrets/{secretId}/fields/{fieldSlug}");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            var fieldResponse = JsonSerializer.Deserialize<FieldResponse>(json);

            return fieldResponse.Value;
        }

        /// <summary>
        /// Retrieve a full secret by ID.
        /// </summary>
        /// <param name="secretId">The Secret Server secret ID</param>
        /// <returns>Full secret object with all fields</returns>
        public async Task<SecretModel> GetSecretAsync(int secretId)
        {
            var token = await GetAccessTokenAsync();
            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", token);

            var response = await _httpClient.GetAsync($"{_baseUrl}/api/v1/secrets/{secretId}");
            response.EnsureSuccessStatusCode();

            var json = await response.Content.ReadAsStringAsync();
            return JsonSerializer.Deserialize<SecretModel>(json);
        }

        /// <summary>
        /// Test connectivity to Secret Server.
        /// </summary>
        /// <returns>True if connection successful</returns>
        public async Task<bool> TestConnectionAsync()
        {
            try
            {
                await GetAccessTokenAsync();
                return true;
            }
            catch
            {
                return false;
            }
        }

        public void Dispose()
        {
            _httpClient?.Dispose();
        }

        #region Response Models

        private class TokenResponse
        {
            [JsonPropertyName("access_token")]
            public string AccessToken { get; set; }

            [JsonPropertyName("expires_in")]
            public int ExpiresIn { get; set; }

            [JsonPropertyName("token_type")]
            public string TokenType { get; set; }
        }

        private class FieldResponse
        {
            [JsonPropertyName("itemId")]
            public int ItemId { get; set; }

            [JsonPropertyName("fieldId")]
            public int FieldId { get; set; }

            [JsonPropertyName("fieldName")]
            public string FieldName { get; set; }

            [JsonPropertyName("slug")]
            public string Slug { get; set; }

            [JsonPropertyName("value")]
            public string Value { get; set; }
        }

        #endregion
    }

    /// <summary>
    /// Represents a Secret Server secret.
    /// </summary>
    public class SecretModel
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("folderId")]
        public int FolderId { get; set; }

        [JsonPropertyName("secretTemplateId")]
        public int SecretTemplateId { get; set; }

        [JsonPropertyName("siteId")]
        public int SiteId { get; set; }

        [JsonPropertyName("active")]
        public bool Active { get; set; }

        [JsonPropertyName("items")]
        public SecretItem[] Items { get; set; }

        /// <summary>
        /// Get field value by name.
        /// </summary>
        public string GetFieldValue(string fieldName)
        {
            foreach (var item in Items)
            {
                if (item.FieldName.Equals(fieldName, StringComparison.OrdinalIgnoreCase))
                {
                    return item.ItemValue;
                }
            }
            return null;
        }
    }

    /// <summary>
    /// Represents a field within a secret.
    /// </summary>
    public class SecretItem
    {
        [JsonPropertyName("fieldId")]
        public int FieldId { get; set; }

        [JsonPropertyName("fieldName")]
        public string FieldName { get; set; }

        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        [JsonPropertyName("itemValue")]
        public string ItemValue { get; set; }

        [JsonPropertyName("isFile")]
        public bool IsFile { get; set; }

        [JsonPropertyName("isNotes")]
        public bool IsNotes { get; set; }

        [JsonPropertyName("isPassword")]
        public bool IsPassword { get; set; }
    }
}
