"""
Mock data for the PAM Migration Control Center.
All structures match the real agent output formats so wiring is a drop-in replacement.
"""

# ── Options ──────────────────────────────────────────────────────────

OPTIONS = {
    "a": {
        "name": "Delinea Secret Server + StrongDM",
        "short": "Option A",
        "color": "blue",
        "target": "Secret Server",
        "auth": "OAuth2 client_credentials",
        "perm_model": "22 → 4 folder roles + 200+ role permissions (LOSSY)",
        "data_structure": "Folder hierarchy + Secret Templates",
        "containers": "Folders",
        "sessions": "StrongDM (Cedar policies, 100+ protocols)",
        "connectors": "Distributed Engine + RPC + StrongDM Relay",
        "integration_path": "Full re-architecture (different auth, endpoints, data format)",
        "audit_retention": "Manual export + archive. CyberArk kept read-only for retention.",
        "risk_profile": "Higher integration risk, more modular architecture",
    },
    "b": {
        "name": "CyberArk Privilege Cloud",
        "short": "Option B",
        "color": "green",
        "target": "Privilege Cloud",
        "auth": "ISPSS Identity / OAuth2 platformtoken",
        "perm_model": "22 → 22 (1:1 parity)",
        "data_structure": "Safe → Account → Platform (same model)",
        "containers": "Safes",
        "sessions": "Cloud PSM (same vendor, session recording in cloud)",
        "connectors": "Connector Server (MQTT TCP 443/8883)",
        "integration_path": "API URL change mostly (same REST surface)",
        "audit_retention": "Preserved — audit logs migrate to Privilege Cloud",
        "risk_profile": "Lower risk, same vendor ecosystem, less modular",
    },
}

# ── Phases ───────────────────────────────────────────────────────────

PHASES = {
    "p0": {
        "id": "p0",
        "name": "Environment Setup & Kick-Off",
        "weeks": "1-6",
        "week_start": 1,
        "week_end": 6,
        "risk": "low",
        "color": "text-muted",
        "agents": [],
        "summary": "Provision infrastructure, configure credentials, validate connectivity, project kick-off",
        "activities": {
            "both": [
                "Project kick-off meeting with all stakeholders",
                "Provision AI Orchestration VM (Ubuntu 22.04, CIS Level 2 hardened)",
                "Install Python 3.12, migration toolkit, dependencies",
                "Configure config.json from template + set environment variables",
                "Configure ServiceNow integration for change management",
                "Set up SIEM forwarding (syslog-ng TLS port 6514)",
                "Run python3 cli.py preflight — verify all connectivity",
                "Initialize migration state file",
            ],
            "a": [
                "Configure Secret Server credentials (SS_CLIENT_ID, SS_CLIENT_SECRET)",
                "Deploy Distributed Engine(s) in target network segments",
                "Provision StrongDM tenant + deploy gateway(s)",
            ],
            "b": [
                "Configure Privilege Cloud credentials (PCLOUD_CLIENT_ID, PCLOUD_CLIENT_SECRET)",
                "Deploy Connector Server(s) for target network segments",
            ],
        },
        "deliverables": [
            "Provisioned AI Orchestration VM with hardened baseline",
            "Verified connectivity to source CyberArk and target PAM",
            "Passing preflight checks for all 15 agents",
            "ServiceNow + SIEM integrations active",
            "Initialized migration state file",
        ],
        "gates": ["g1"],
    },
    "p1": {
        "id": "p1",
        "name": "Discovery & Analysis",
        "weeks": "7-18",
        "week_start": 7,
        "week_end": 18,
        "risk": "low",
        "color": "green",
        "agents": [11, 1, 9, 12, 2, 3],
        "summary": "Full inventory — accounts, dependencies, NHIs, gaps, permissions, wave classification",
        "activities": {
            "both": [
                "W7-9: Agent 11 (Source Adapter) — connect to CyberArk PVWA, normalize inventory",
                "W10-12: Agent 01 (Discovery) — full environment scan, NHI detection (3 signals)",
                "W13-15: Agent 09 (Dependency Mapper) — IIS logs, app → account → safe mapping",
                "W13-15: Agent 12 (NHI Handler) — weighted multi-signal scoring, rotation policies",
                "W16-18: Agent 02 (Gap Analysis) — 10-domain maturity, 4 compliance frameworks",
                "W16-18: Agent 03 (Permissions) — full permission audit of all safe members",
            ],
            "a": [
                "Agent 02 identifies Secret Server template gaps for custom platforms",
                "Agent 03 maps 22 CyberArk permissions → 4 SS roles (flags escalation risk)",
            ],
            "b": [
                "Agent 02 identifies Cloud CPM connectivity per network segment",
                "Agent 03 verifies 22 → 22 permission parity with Privilege Cloud",
            ],
        },
        "deliverables": [
            "Discovery manifest (JSON): accounts, safes, platforms, NHIs, integrations",
            "Dependency graph (JSON): application-to-account-to-safe mappings",
            "NHI classification report: confidence scores, types, rotation policies",
            "Gap analysis report: 10-domain scores, compliance mapping (PCI/NIST/HIPAA/SOX)",
            "Permission audit report: per-member mapping with escalation flags",
            "Wave classification: 5-wave migration order by risk",
        ],
        "gates": ["g2", "g3"],
    },
    "p2": {
        "id": "p2",
        "name": "Infrastructure & Staging",
        "weeks": "19-28",
        "week_start": 19,
        "week_end": 28,
        "risk": "medium",
        "color": "blue",
        "agents": [13, 10],
        "summary": "Deploy target infrastructure, validate platforms/templates, run 10-assertion staging pipeline",
        "activities": {
            "both": [
                "W23-25: Agent 13 (Platform Plugins) — validate platform/template coverage",
                "W26-28: Agent 10 (Staging Validation) — 10-assertion mini-ETL pipeline",
            ],
            "a": [
                "Configure Secret Server OAuth2 authentication",
                "Deploy Distributed Engines in all target network segments",
                "Deploy StrongDM relays in resource-near segments",
                "Create custom templates for unmapped CyberArk platforms",
                "Configure RPC connection components per template",
            ],
            "b": [
                "Configure ISPSS Identity / OAuth2 authentication",
                "Verify Connector Server connectivity to all target networks",
                "Configure Cloud CPM policies per platform",
                "Deploy custom connection components for non-standard platforms",
            ],
        },
        "deliverables": [
            "Target environment fully deployed and configured",
            "Platform/template validation report (Agent 13)",
            "Staging validation report: 10/10 assertions passed (Agent 10)",
            "Rollback procedure tested in staging",
        ],
        "gates": ["g4"],
    },
    "p3": {
        "id": "p3",
        "name": "Structure Migration",
        "weeks": "29-38",
        "week_start": 29,
        "week_end": 38,
        "risk": "low",
        "color": "purple",
        "agents": [3, 14],
        "summary": "Create organizational structure in target, onboard applications, prepare pilot",
        "activities": {
            "both": [
                "W33-35: Agent 14 (Onboarding) — 10-step application onboarding pipeline",
                "W36-38: Verify structure, remediate issues, prepare pilot wave",
                "Submit ServiceNow change request for pilot migration window",
            ],
            "a": [
                "Create parent /Imported/ folder in Secret Server",
                "Create per-safe child folders: /Imported/{SafeName}/",
                "Apply translated permissions via folder-permissions API (22→4 roles)",
                "Flag escalation cases for human review",
            ],
            "b": [
                "Create safes in Privilege Cloud (same names as source)",
                "Map platform policies via Platforms/Targets API",
                "Apply permissions via Safe Members API (22→22 parity)",
            ],
        },
        "deliverables": [
            "Organizational structure created in target environment",
            "Permission mapping verification report",
            "Application onboarding results (Agent 14)",
            "Approved ServiceNow change request for pilot",
        ],
        "gates": ["g5"],
    },
    "p4": {
        "id": "p4",
        "name": "Test & Pilot",
        "weeks": "39-46",
        "week_start": 39,
        "week_end": 46,
        "risk": "medium",
        "color": "amber",
        "agents": [4, 5],
        "summary": "Migrate ~50 test/dev accounts, validate full pipeline, test rollback. BLOCKS production.",
        "activities": {
            "both": [
                "W39-42: Agent 04 (Migration Pipeline) — pilot wave execution (~50 accounts)",
                "W43-46: Agent 05 (Heartbeat) — 10-check post-migration validation",
                "Test rollback: verify delete works, accounts removed from target",
                "Document timing metrics for production wave planning",
            ],
            "a": [
                "7-step pipeline: Freeze→Export→Transform→Create Folders→Import→Heartbeat→Unfreeze",
                "Transform includes: Safe→Folder, Platform→Template mapping",
            ],
            "b": [
                "6-step pipeline: Freeze→Export→Transform→Create Safes→Import→Unfreeze",
                "Transform includes: URL rewrite for Privilege Cloud endpoints",
            ],
        },
        "deliverables": [
            "Pilot pipeline execution report (Agent 04)",
            "Pilot validation report: 10-check results (Agent 05)",
            "Rollback procedure documented and tested",
            "Timing metrics for production wave sizing",
            "Approved ServiceNow change request for production waves",
        ],
        "gates": ["g6"],
    },
    "p5": {
        "id": "p5",
        "name": "Production Migration",
        "weeks": "47-62",
        "week_start": 47,
        "week_end": 62,
        "risk": "high",
        "color": "red",
        "agents": [4, 5, 6, 7, 12, 14],
        "summary": "5-wave production migration with per-wave human approval gates",
        "activities": {
            "both": [
                "W47-50: Wave 1 — Standard/Test/Dev accounts (20-30%)",
                "W51-53: Wave 2 — Infrastructure accounts (15-20%)",
                "W54-56: Wave 3 — NHIs without CCP/AAM (15-25%) — Agent 12 rotation policies",
                "W57-59: Wave 4 — NHIs with CCP/AAM (10-15%) — Agent 06 prepares replacement code",
                "W60-62: Wave 5 — Remaining + compliance report + final reconciliation",
                "Per-wave: Agent 04 runs ETL, Agent 05 validates, human gate approves",
            ],
            "a": [
                "Wave 4: Agent 06 generates replacement code (Python/Java/C#/PowerShell) for SS API",
                "Wave 5: Agent 07 compliance report includes SS-specific risks (audit discontinuity, permission loss)",
            ],
            "b": [
                "Wave 4: Agent 06 updates CCP/AAM endpoints (mostly URL change, same API surface)",
                "Wave 5: Agent 07 compliance report — audit logs preserved in Privilege Cloud",
            ],
        },
        "deliverables": [
            "Per-wave migration reports (Agent 04): success/failure counts, batch details",
            "Per-wave validation reports (Agent 05): 10-check results per wave",
            "Integration change registry (Agent 06): per-app repointing status",
            "NHI rotation confirmation (Agent 12): rotation active in target",
            "Compliance report (Agent 07): 4-framework evidence package",
        ],
        "gates": ["g7", "g8", "g9", "g10", "g11"],
    },
    "p6": {
        "id": "p6",
        "name": "Parallel Running & Cutover",
        "weeks": "63-76",
        "week_start": 63,
        "week_end": 76,
        "risk": "medium",
        "color": "cyan",
        "agents": [5, 6, 7, 15],
        "summary": "Dual operation, gradual traffic shift (10%→50%→90%→100%), integration cutover, final approval",
        "activities": {
            "both": [
                "W63-66: Agent 15 (Hybrid Fleet) — parallel-run setup, 10% target traffic",
                "W67-69: Agent 06 (Integration) — repoint remaining integrations",
                "W70-72: Gradual traffic shift — 50% then 90% target",
                "W73-76: Agent 05 final validation, Agent 07 final compliance, cutover decision",
                "Set source environment to read-only",
            ],
            "a": [
                "Agent 06: full re-architecture of CCP/AAM → SS REST API + OAuth2",
                "Deploy generated replacement code per application",
                "Configure StrongDM JIT access policies for session management",
            ],
            "b": [
                "Agent 06: update CCP/AAM endpoints to Privilege Cloud URLs",
                "Configure cert auth → ISPSS OAuth2 where needed",
            ],
        },
        "deliverables": [
            "Parallel-run metrics report (Agent 15): error rates, latency, discrepancies",
            "Integration cutover registry (Agent 06): per-app sign-off status",
            "Final validation report (Agent 05): all migrated accounts verified",
            "Final compliance report (Agent 07): full evidence package",
        ],
        "gates": ["g12", "g13"],
    },
    "p7": {
        "id": "p7",
        "name": "Decommission & Close-Out",
        "weeks": "77-80",
        "week_start": 77,
        "week_end": 80,
        "risk": "medium",
        "color": "text-muted",
        "agents": [7, 8],
        "summary": "Archive source data, decommission infrastructure, lessons learned, final sign-off",
        "activities": {
            "both": [
                "W77-78: Agent 07 (Compliance) — final close-out report, lessons learned",
                "W79-80: Agent 08 (Runbook) — ordered decommission sequence",
                "Knowledge transfer to operations team",
                "Decommission AI Orchestration VM (or repurpose)",
            ],
            "a": [
                "Archive CyberArk audit logs (do NOT transfer to SS — manual export)",
                "Archive PSM recordings (StrongDM replaces going forward)",
                "Keep CyberArk vault read-only for audit retention (1-7 years)",
                "Decommission: PSM → CPM → PVWA → Vault (ordered, approval each step)",
            ],
            "b": [
                "Migrate audit logs to Privilege Cloud",
                "Transfer PSM recordings to cloud storage",
                "Decommission: PSM → CPM → PVWA → Vault (ordered, approval each step)",
            ],
        },
        "deliverables": [
            "Archived audit logs and PSM recordings",
            "Final compliance close-out report",
            "Lessons learned document",
            "Operations handoff documentation",
            "Project closure report with migration metrics",
        ],
        "gates": ["g14"],
    },
}

# ── Agents ───────────────────────────────────────────────────────────

AGENTS = {
    "1": {
        "num": "01", "name": "Discovery", "phases": ["p1"], "weeks": "W10-12",
        "status": "complete",
        "desc": "Full CyberArk environment scan. Enumerates safes (GET /Safes), platforms (GET /Platforms/Targets), accounts. Multi-signal NHI detection: platform-based + name patterns + safe patterns.",
        "inputs": ["PVWA REST API access", "Audit logs (90 days)"],
        "outputs": ["Discovery manifest (JSON)", "NHI preliminary list"],
        "api_calls": ["GET /Safes", "GET /Safes/{name}/Members", "GET /Platforms/Targets", "GET /Applications"],
        "gates": [], "blocked_by": [11],
    },
    "2": {
        "num": "02", "name": "Gap Analysis", "phases": ["p1"], "weeks": "W16-18",
        "status": "complete",
        "desc": "10-domain maturity assessment: auth, session, lifecycle, platform, CPM, safe structure, permissions, NHI, integration, audit. Maps to PCI-DSS v4.0, NIST 800-53 Rev5, HIPAA, SOX.",
        "inputs": ["Discovery manifest (Agent 01)"],
        "outputs": ["Gap analysis report", "Compliance mapping"],
        "api_calls": [],
        "gates": [], "blocked_by": [1],
    },
    "3": {
        "num": "03", "name": "Permissions", "phases": ["p1", "p3"], "weeks": "W16-18, W29-32",
        "status": "active",
        "desc": "Permission audit and structure migration. P1: audits all 22 CyberArk safe permissions per member. P3: creates structure in target with correct permission mappings.",
        "inputs": ["Discovery manifest (Agent 01)", "Target API access"],
        "outputs": ["Permission mapping report", "Escalation flags", "Structure in target"],
        "api_calls": ["GET /Safes/{name}/Members", "POST /Safes (Option B)", "POST /api/v1/folder-permissions (Option A)"],
        "gates": ["g5"], "blocked_by": [1],
    },
    "4": {
        "num": "04", "name": "Migration Pipeline", "phases": ["p4", "p5"], "weeks": "W39-62",
        "status": "pending",
        "desc": "Core ETL engine. Batch processing with 120-min watchdog timer. Steps: Freeze→Export→Transform→Import→Heartbeat→Unfreeze. Rate limiting (100/min). Emergency unfreeze on exception.",
        "inputs": ["Agent 09 dependency map", "Agent 10 staging pass", "Agent 12 NHI classifications"],
        "outputs": ["Per-wave migration reports", "Batch execution logs"],
        "api_calls": ["POST /Accounts/{id}/Password/Retrieve", "POST /Safes/{name}/Members (Option B)", "POST /api/v1/secrets (Option A)"],
        "gates": ["g6"], "blocked_by": [10],
    },
    "5": {
        "num": "05", "name": "Heartbeat", "phases": ["p4", "p5", "p6"], "weeks": "W43-76",
        "status": "pending",
        "desc": "10-check post-migration validation. Count comparison (<1% variance), heartbeat verification (>95%), permission mapping, metadata integrity, audit continuity, rollback testing.",
        "inputs": ["Migrated accounts in target"],
        "outputs": ["Validation reports per wave"],
        "api_calls": ["POST /Accounts/{id}/Verify (Option B)", "POST /api/v1/secrets/{id}/heartbeat (Option A)"],
        "gates": [], "blocked_by": [4],
    },
    "6": {
        "num": "06", "name": "Integration", "phases": ["p5", "p6"], "weeks": "W57-69",
        "status": "pending",
        "desc": "CCP/AAM integration repointing. Scans codebases for CyberArk API calls. Generates replacement code (Python, Java, C#, PowerShell). Feature-flag routing for safe rollback.",
        "inputs": ["Integration inventory (Agent 09)", "Generated code templates"],
        "outputs": ["Integration change registry", "Replacement code packages"],
        "api_calls": [],
        "gates": ["g12"], "blocked_by": [9],
    },
    "7": {
        "num": "07", "name": "Compliance", "phases": ["p5", "p6", "p7"], "weeks": "W60-78",
        "status": "pending",
        "desc": "Compliance reporting. Maps migration evidence to PCI-DSS v4.0, NIST 800-53 Rev5, HIPAA, SOX. Generates audit-ready evidence packages.",
        "inputs": ["All migration reports", "All validation reports"],
        "outputs": ["Per-wave compliance reports", "Final close-out report"],
        "api_calls": [],
        "gates": ["g14"], "blocked_by": [],
    },
    "8": {
        "num": "08", "name": "Runbook", "phases": ["p7"], "weeks": "W79-80",
        "status": "pending",
        "desc": "Phase gate management and decommission sequencing. Manages ordered infrastructure shutdown: PSM→CPM→PVWA→Vault. Human approval at each step.",
        "inputs": ["All prior reports", "Compliance close-out"],
        "outputs": ["Decommission confirmation", "Project closure"],
        "api_calls": [],
        "gates": ["g14"], "blocked_by": [7],
    },
    "9": {
        "num": "09", "name": "Dependency Mapper", "phases": ["p1"], "weeks": "W13-15",
        "status": "complete",
        "desc": "Builds application dependency graph. Scans IIS logs, Windows services, scheduled tasks, Jenkins pipelines, scripts, config files for CyberArk API calls.",
        "inputs": ["Discovery manifest (Agent 01)", "IIS logs", "System scans"],
        "outputs": ["Dependency graph (JSON)", "Application-to-account mappings"],
        "api_calls": [],
        "gates": [], "blocked_by": [1],
    },
    "10": {
        "num": "10", "name": "Staging Validation", "phases": ["p2"], "weeks": "W26-28",
        "status": "active",
        "desc": "10-assertion staging pipeline. Runs mini-ETL on ~100 sample accounts. Hard-blocks Agent 04 production migration if any assertion fails.",
        "inputs": ["Target environment", "Sample accounts (20 per wave type)"],
        "outputs": ["Staging validation report (10 assertions)"],
        "api_calls": ["POST /Safes (create)", "POST /Accounts (import)", "DELETE /Accounts (rollback test)"],
        "gates": ["g4"], "blocked_by": [13],
    },
    "11": {
        "num": "11", "name": "Source Adapter", "phases": ["p1"], "weeks": "W7-9",
        "status": "complete",
        "desc": "Multi-vendor source adapter. Connects to CyberArk PVWA, extracts raw data, produces NormalizedAccount canonical inventory. Supports CyberArk, BeyondTrust, Secret Server, HashiCorp, cloud vaults.",
        "inputs": ["Source PAM API credentials"],
        "outputs": ["Normalized inventory (NormalizedAccount, NormalizedContainer, NormalizedPlatform)"],
        "api_calls": ["POST /Auth/{type}/Logon", "GET /Accounts?limit=1000", "GET /Safes"],
        "gates": [], "blocked_by": [],
    },
    "12": {
        "num": "12", "name": "NHI Handler", "phases": ["p1", "p5"], "weeks": "W13-15, W54-56",
        "status": "complete",
        "desc": "Non-Human Identity classification. Weighted multi-signal scoring (platform 35%, name 20%, container 10%, dependency 25%, audit 10%). 7 NHI subtypes with per-type rotation strategies.",
        "inputs": ["Discovery manifest", "Dependency graph", "Audit logs"],
        "outputs": ["NHI classification report", "Per-type rotation policies"],
        "api_calls": [],
        "gates": ["g2"], "blocked_by": [1, 9],
    },
    "13": {
        "num": "13", "name": "Platform Plugins", "phases": ["p2"], "weeks": "W23-25",
        "status": "active",
        "desc": "Validates target platform/template coverage against source. Deploys connection components. Auto-creates missing templates in Secret Server.",
        "inputs": ["Discovery manifest (platforms list)"],
        "outputs": ["Platform validation report", "Connection component deployment log"],
        "api_calls": ["GET /Platforms/Targets (Option B)", "GET /api/v1/secret-templates (Option A)"],
        "gates": [], "blocked_by": [2],
    },
    "14": {
        "num": "14", "name": "Onboarding", "phases": ["p3", "p5"], "weeks": "W33-35, W60-62",
        "status": "pending",
        "desc": "10-step application onboarding pipeline. Validate→Create Structure→Permissions→Resolve Template→Create Account→Assign Engine→Set Rotation→Verify Heartbeat→Generate Instructions→Report.",
        "inputs": ["Application requests", "Structure in target"],
        "outputs": ["Onboarding report", "Per-app retrieval instructions"],
        "api_calls": [],
        "gates": [], "blocked_by": [3],
    },
    "15": {
        "num": "15", "name": "Hybrid Fleet", "phases": ["p6"], "weeks": "W63-72",
        "status": "pending",
        "desc": "Parallel-run manager. Monitors source+target environments simultaneously. Gradual traffic shift (10%→50%→90%→100%). Automatic rollback triggers if failure threshold exceeded.",
        "inputs": ["All migrated accounts", "Integration registry"],
        "outputs": ["Parallel-run metrics report", "Cutover recommendation"],
        "api_calls": [],
        "gates": ["g13"], "blocked_by": [],
    },
    "dx1": {
        "num": "DX-01", "name": "DX Portal", "phases": ["p1", "p2", "p3", "p4", "p5", "p6"],
        "weeks": "W10-76", "status": "active",
        "desc": "PAM Portal development. Spring Boot 3.2 + Java 17 + Thymeleaf. PamVendorAdapter interface with 12 methods. Vendor-agnostic — zero portal changes when adding new vendor.",
        "inputs": ["Requirements", "PamVendorAdapter contract"],
        "outputs": ["Portal WAR/container", "REST API gateway", "OpenAPI spec"],
        "api_calls": [],
        "gates": [], "blocked_by": [],
    },
    "dx2": {
        "num": "DX-02", "name": "Adapter Gen", "phases": ["p2", "p3", "p5"],
        "weeks": "W21-58", "status": "active",
        "desc": "Adapter code generation. Produces replacement client libraries for CCP/AAM integration migration. Supports Python, Java, C#, PowerShell output.",
        "inputs": ["Integration inventory (Agent 09)", "Code templates"],
        "outputs": ["Generated client code packages"],
        "api_calls": [],
        "gates": [], "blocked_by": [9],
    },
}

# ── Waves ────────────────────────────────────────────────────────────

WAVES = {
    "1": {
        "name": "Standard Accounts",
        "risk": "low",
        "type": "Test/Dev, sandbox, PoC, lab, demo",
        "account_pct": "20-30%",
        "account_count": 698,
        "weeks": "W47-50",
        "agents": [4, 5],
        "description": "Lowest risk — test/dev environments, sandbox accounts, proof-of-concept. Validates production pipeline at scale.",
        "gate": "g7",
        "status": "pending",
        "etl_steps_a": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE FOLDERS", "IMPORT", "HEARTBEAT", "UNFREEZE"],
        "etl_steps_b": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE SAFES", "IMPORT", "UNFREEZE"],
    },
    "2": {
        "name": "Infrastructure Accounts",
        "risk": "medium",
        "type": "Domain admins, DB service, network devices",
        "account_pct": "15-20%",
        "account_count": 498,
        "weeks": "W51-53",
        "agents": [4, 5],
        "description": "Domain admin accounts, database service accounts, network infrastructure. Tight change windows required.",
        "gate": "g8",
        "status": "pending",
        "etl_steps_a": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE FOLDERS", "IMPORT", "HEARTBEAT", "UNFREEZE"],
        "etl_steps_b": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE SAFES", "IMPORT", "UNFREEZE"],
    },
    "3": {
        "name": "NHIs (No CCP/AAM)",
        "risk": "high",
        "type": "Service accounts, API keys (no active integrations)",
        "account_pct": "15-25%",
        "account_count": 554,
        "weeks": "W54-56",
        "agents": [4, 5, 12],
        "description": "Non-human identities without CCP/AAM integrations. Agent 12 provides rotation policies. Dependency graph respected.",
        "gate": "g9",
        "status": "pending",
        "etl_steps_a": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE FOLDERS", "IMPORT", "HEARTBEAT", "UNFREEZE"],
        "etl_steps_b": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE SAFES", "IMPORT", "UNFREEZE"],
    },
    "4": {
        "name": "NHIs With CCP/AAM",
        "risk": "critical",
        "type": "Active application dependencies",
        "account_pct": "10-15%",
        "account_count": 350,
        "weeks": "W57-59",
        "agents": [4, 5, 6],
        "description": "HIGHEST RISK — service accounts with active CCP/AAM integrations. Agent 06 prepares replacement code BEFORE migration. Per-app sign-off required.",
        "gate": "g10",
        "status": "pending",
        "etl_steps_a": ["FREEZE", "EXPORT", "TRANSFORM", "RECODE INTEGRATIONS", "CREATE FOLDERS", "IMPORT", "HEARTBEAT", "UNFREEZE"],
        "etl_steps_b": ["FREEZE", "EXPORT", "TRANSFORM", "UPDATE ENDPOINTS", "CREATE SAFES", "IMPORT", "UNFREEZE"],
    },
    "5": {
        "name": "Final Cleanup",
        "risk": "medium",
        "type": "Stragglers, exceptions, compliance verification",
        "account_pct": "Remaining",
        "account_count": 747,
        "weeks": "W60-62",
        "agents": [4, 5, 7, 14],
        "description": "Remaining accounts, newly discovered applications, compliance report generation, 100% coverage reconciliation.",
        "gate": "g11",
        "status": "pending",
        "etl_steps_a": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE FOLDERS", "IMPORT", "HEARTBEAT", "UNFREEZE"],
        "etl_steps_b": ["FREEZE", "EXPORT", "TRANSFORM", "CREATE SAFES", "IMPORT", "UNFREEZE"],
    },
}

# ── Gates ────────────────────────────────────────────────────────────

GATES = [
    {
        "id": "g1", "name": "Project Kick-off", "phase": "p0", "week": 6,
        "approvers": ["Exec Sponsor", "NOC/Infra"],
        "status": "passed",
        "requirements": "Executive sponsor approves charter, timeline, resource allocation. RACI matrix signed by all stakeholders.",
    },
    {
        "id": "g2", "name": "NHI Classification Review", "phase": "p1", "week": 15,
        "approvers": ["PAM Engineer", "App Owners"],
        "status": "passed",
        "requirements": "SME validates high-risk NHI classifications. Confirm NHI owners, dependency chains, rotation requirements. App owners acknowledge within 5 business days.",
    },
    {
        "id": "g3", "name": "Discovery Sign-off", "phase": "p1", "week": 18,
        "approvers": ["PAM Engineer", "Compliance", "Exec Sponsor"],
        "status": "passed",
        "requirements": "Review and approve: discovery manifest, dependency graph, NHI classifications, gap analysis, permission audit. All must be signed before P2.",
    },
    {
        "id": "g4", "name": "Staging Approval", "phase": "p2", "week": 28,
        "approvers": ["PAM Engineer", "NOC/Infra"],
        "status": "active",
        "requirements": "Agent 10 staging validation: all 10 assertions passed. Target environment confirmed ready for production data.",
    },
    {
        "id": "g5", "name": "Structure Approval", "phase": "p3", "week": 38,
        "approvers": ["PAM Engineer", "App Owners", "CAB"],
        "status": "pending",
        "requirements": "Organizational structure verified in target. Permission mappings confirmed correct. CAB approves pilot migration change request.",
    },
    {
        "id": "g6", "name": "Pilot Results Approval", "phase": "p4", "week": 46,
        "approvers": ["PAM Engineer", "App Owners", "Exec Sponsor"],
        "status": "pending",
        "requirements": "Heartbeat success >95%. Rollback procedure tested. Application owners confirm access works in target. BLOCKS ALL PRODUCTION WAVES.",
    },
    {
        "id": "g7", "name": "Wave 1 Approval", "phase": "p5", "week": 50,
        "approvers": ["PAM Engineer", "App Owners"],
        "status": "pending",
        "requirements": "Wave 1 heartbeat >95%. Standard accounts verified functional in target.",
    },
    {
        "id": "g8", "name": "Wave 2 Approval", "phase": "p5", "week": 53,
        "approvers": ["PAM Engineer", "NOC/Infra"],
        "status": "pending",
        "requirements": "Infrastructure team validates critical service accounts. Domain admin access confirmed.",
    },
    {
        "id": "g9", "name": "Wave 3 Approval", "phase": "p5", "week": 56,
        "approvers": ["PAM Engineer", "App Owners", "Compliance"],
        "status": "pending",
        "requirements": "NHI accounts functional in target. Rotation policies confirmed active. NHI owners validated within 48 hours.",
    },
    {
        "id": "g10", "name": "Wave 4 Approval", "phase": "p5", "week": 59,
        "approvers": ["PAM Engineer", "App Owners"],
        "status": "pending",
        "requirements": "CCP/AAM integrations working with target. Per-application developer sign-off required. Replacement code deployed and tested.",
    },
    {
        "id": "g11", "name": "Production Complete", "phase": "p5", "week": 62,
        "approvers": ["PAM Engineer", "Compliance", "App Owners"],
        "status": "pending",
        "requirements": "100% account coverage (source count = target count). Compliance report reviewed. All application owners confirm.",
    },
    {
        "id": "g12", "name": "Integration Cutover", "phase": "p6", "week": 69,
        "approvers": ["App Owners", "Dev Leads"],
        "status": "pending",
        "requirements": "Each application owner confirms integration works with target. Developer sign-off per application. Rollback code prepared.",
    },
    {
        "id": "g13", "name": "Cutover Approval", "phase": "p6", "week": 76,
        "approvers": ["CAB", "Exec Sponsor", "Compliance"],
        "status": "pending",
        "requirements": "Final validation report, compliance evidence, parallel-run metrics, all app owner sign-offs. Source set to read-only.",
    },
    {
        "id": "g14", "name": "Final Sign-off", "phase": "p7", "week": 80,
        "approvers": ["Exec Sponsor", "Compliance", "Security"],
        "status": "pending",
        "requirements": "All deliverables archived. Decommission complete. Audit retention confirmed by legal. Infrastructure decommission verified.",
    },
    {
        "id": "g15", "name": "DX Architecture Review", "phase": "dx", "week": 20,
        "approvers": ["Architecture Board"],
        "status": "passed",
        "requirements": "PamVendorAdapter interface contract approved. OpenAPI spec reviewed. Deployment topology signed off.",
    },
    {
        "id": "g16", "name": "DX MVP Walkthrough", "phase": "dx", "week": 34,
        "approvers": ["PAM Engineer", "UX"],
        "status": "pending",
        "requirements": "Login flow, secret browsing, credential checkout, audit log viewing validated by stakeholders.",
    },
    {
        "id": "g17", "name": "DX Production Cutover", "phase": "dx", "week": 74,
        "approvers": ["Operations", "Security"],
        "status": "pending",
        "requirements": "Portal uptime SLA met. All adapters green. Load test passed. Security scan clean.",
    },
]

# ── Deliverables (sample agent outputs in real format) ───────────────

DELIVERABLES = {
    "p1": {
        "discovery_manifest": {
            "name": "Discovery Manifest",
            "agent": "01",
            "format": "JSON",
            "data": {
                "summary": {
                    "total_accounts": 2847,
                    "human_accounts": 2435,
                    "nhi_accounts": 412,
                    "total_safes": 142,
                    "total_platforms": 23,
                    "total_integrations": 89,
                    "scan_duration_seconds": 347,
                },
                "safes": [
                    {"name": "Production-Windows", "member_count": 12, "account_count": 234},
                    {"name": "Production-Linux", "member_count": 8, "account_count": 189},
                    {"name": "Production-Database", "member_count": 6, "account_count": 156},
                    {"name": "CI-CD-Automation", "member_count": 4, "account_count": 87},
                    {"name": "Network-Infrastructure", "member_count": 5, "account_count": 112},
                    {"name": "Cloud-AWS", "member_count": 7, "account_count": 198},
                    {"name": "Cloud-Azure", "member_count": 6, "account_count": 145},
                    {"name": "Development-Test", "member_count": 15, "account_count": 423},
                    {"name": "Service-Accounts-Prod", "member_count": 3, "account_count": 312},
                    {"name": "DBA-Credentials", "member_count": 4, "account_count": 89},
                ],
                "platforms": [
                    {"id": "WinServerLocal", "name": "Windows Server Local", "count": 890},
                    {"id": "WinDomain", "name": "Windows Domain", "count": 456},
                    {"id": "UnixSSH", "name": "Unix via SSH", "count": 378},
                    {"id": "UnixSSHKeys", "name": "Unix SSH Keys", "count": 123},
                    {"id": "Oracle", "name": "Oracle Database", "count": 89},
                    {"id": "MSSql", "name": "MS SQL Server", "count": 156},
                    {"id": "MySQL", "name": "MySQL", "count": 67},
                    {"id": "AWSAccessKeys", "name": "AWS Access Keys", "count": 198},
                    {"id": "AzureServicePrincipal", "name": "Azure Service Principal", "count": 145},
                    {"id": "WinServiceAccount", "name": "Windows Service Account", "count": 234},
                    {"id": "CustomWebApp", "name": "Custom Web Application", "count": 45},
                    {"id": "CiscoDevice", "name": "Cisco Network Device", "count": 66},
                ],
                "nhis": [
                    {"id": "acc-1001", "name": "svc-jenkins-prod", "safe": "CI-CD-Automation", "platform": "WinServiceAccount", "confidence": 0.95, "type": "CI/CD", "detection": "platform+name+safe"},
                    {"id": "acc-1002", "name": "svc-ansible-tower", "safe": "CI-CD-Automation", "platform": "UnixSSH", "confidence": 0.92, "type": "CI/CD", "detection": "name+safe"},
                    {"id": "acc-1003", "name": "app-payroll-api", "safe": "Service-Accounts-Prod", "platform": "WinServiceAccount", "confidence": 0.88, "type": "Application", "detection": "name+platform"},
                    {"id": "acc-1004", "name": "svc-monitoring-01", "safe": "Service-Accounts-Prod", "platform": "UnixSSH", "confidence": 0.90, "type": "Monitoring", "detection": "name"},
                    {"id": "acc-1005", "name": "bot-backup-nightly", "safe": "Service-Accounts-Prod", "platform": "WinServiceAccount", "confidence": 0.87, "type": "Scheduled Task", "detection": "name+platform"},
                ],
                "integrations": [
                    {"type": "CCP_AAM", "app_name": "Jenkins CI/CD", "account_ids": ["acc-1001", "acc-1002"], "protocol": "REST", "auth": "certificate"},
                    {"type": "CCP_AAM", "app_name": "Ansible Tower", "account_ids": ["acc-1002"], "protocol": "REST", "auth": "certificate"},
                    {"type": "CCP_AAM", "app_name": "Payroll Application", "account_ids": ["acc-1003"], "protocol": "CCP", "auth": "app_id"},
                    {"type": "SIEM", "app_name": "Splunk", "account_ids": [], "protocol": "syslog", "auth": "tls"},
                    {"type": "TICKETING", "app_name": "ServiceNow", "account_ids": [], "protocol": "REST", "auth": "oauth2"},
                ],
            },
        },
        "dependency_graph": {
            "name": "Dependency Graph",
            "agent": "09",
            "format": "JSON",
            "data": {
                "total_dependencies": 89,
                "accounts_with_deps": 67,
                "dependency_types": {"CCP_AAM": 34, "IIS_AppPool": 18, "Windows_Service": 15, "Scheduled_Task": 12, "Jenkins_Pipeline": 10},
                "top_dependencies": [
                    {"account_id": "acc-1001", "name": "svc-jenkins-prod", "consumers": ["Jenkins CI/CD", "GitLab Runner", "Terraform Cloud"], "dep_count": 3},
                    {"account_id": "acc-1003", "name": "app-payroll-api", "consumers": ["Payroll Application", "HR Portal"], "dep_count": 2},
                    {"account_id": "acc-1004", "name": "svc-monitoring-01", "consumers": ["Nagios", "Grafana", "PagerDuty"], "dep_count": 3},
                ],
            },
        },
        "nhi_classification": {
            "name": "NHI Classification Report",
            "agent": "12",
            "format": "JSON",
            "data": {
                "total_nhis": 412,
                "by_risk": {"critical": 34, "high": 89, "medium": 178, "low": 111},
                "by_type": {"CI/CD": 87, "Application": 112, "Monitoring": 45, "Scheduled Task": 67, "API Key": 56, "Service Account": 34, "Bot": 11},
                "rotation_policies": [
                    {"type": "CI/CD", "interval_days": 90, "strategy": "coordinated_rotation", "requires_downtime": False},
                    {"type": "Application", "interval_days": 180, "strategy": "dual_credential", "requires_downtime": False},
                    {"type": "Monitoring", "interval_days": 365, "strategy": "standard_rotation", "requires_downtime": False},
                ],
            },
        },
        "gap_analysis": {
            "name": "Gap Analysis Report",
            "agent": "02",
            "format": "JSON",
            "data": {
                "overall_score": 7.2,
                "domains": [
                    {"name": "Authentication", "score": 8, "max": 10, "status": "good"},
                    {"name": "Session Management", "score": 7, "max": 10, "status": "good"},
                    {"name": "Lifecycle Management", "score": 6, "max": 10, "status": "warning"},
                    {"name": "Platform Coverage", "score": 8, "max": 10, "status": "good"},
                    {"name": "CPM/Rotation", "score": 7, "max": 10, "status": "good"},
                    {"name": "Safe Structure", "score": 9, "max": 10, "status": "good"},
                    {"name": "Permissions", "score": 6, "max": 10, "status": "warning"},
                    {"name": "NHI Management", "score": 5, "max": 10, "status": "critical"},
                    {"name": "Integration", "score": 7, "max": 10, "status": "good"},
                    {"name": "Audit/Compliance", "score": 9, "max": 10, "status": "good"},
                ],
                "compliance_gaps": [
                    {"framework": "PCI-DSS v4.0", "requirement": "8.6.1", "desc": "NHI inventory not complete", "severity": "high"},
                    {"framework": "NIST 800-53", "requirement": "AC-2(4)", "desc": "Automated NHI lifecycle not implemented", "severity": "medium"},
                ],
            },
        },
        "permission_audit": {
            "name": "Permission Audit",
            "agent": "03",
            "format": "JSON",
            "data": {
                "total_members_audited": 234,
                "escalation_flags": 12,
                "permission_stats": {
                    "full_admin": 18,
                    "power_user": 45,
                    "standard_user": 134,
                    "read_only": 37,
                },
            },
        },
    },
    "p2": {
        "staging_validation": {
            "name": "Staging Validation Report",
            "agent": "10",
            "format": "JSON",
            "data": {
                "overall": "passed",
                "sample_size": 100,
                "assertions": [
                    {"name": "account_count", "passed": True, "detail": "100/100 accounts imported successfully"},
                    {"name": "safes_created", "passed": True, "detail": "5/5 test safes created in staging"},
                    {"name": "permissions_applied", "passed": True, "detail": "All safe member permissions verified"},
                    {"name": "heartbeat_pass", "passed": True, "detail": "98/100 heartbeat verified (98.0%)"},
                    {"name": "secrets_retrievable", "passed": True, "detail": "100/100 passwords retrievable"},
                    {"name": "linked_accounts", "passed": True, "detail": "12/12 logon/reconcile links intact"},
                    {"name": "platform_assignments", "passed": True, "detail": "All platform IDs valid in staging"},
                    {"name": "audit_events", "passed": True, "detail": "Audit log entries generated for all operations"},
                    {"name": "no_orphans", "passed": True, "detail": "0 orphaned accounts found"},
                    {"name": "rollback", "passed": True, "detail": "All 100 accounts deleted and verified gone"},
                ],
                "failed_count": 0,
            },
        },
        "platform_validation": {
            "name": "Platform Validation Report",
            "agent": "13",
            "format": "JSON",
            "data": {
                "total_platforms": 23,
                "mapped": 20,
                "custom_required": 3,
                "custom_platforms": [
                    {"source": "CustomWebApp", "status": "template_created", "template": "Web Application Account"},
                    {"source": "CiscoDevice", "status": "template_created", "template": "Cisco Network Device"},
                    {"source": "F5BigIP", "status": "pending", "template": None},
                ],
            },
        },
    },
    "p4": {
        "pilot_report": {
            "name": "Pilot Migration Report",
            "agent": "04",
            "format": "JSON",
            "data": {
                "wave": "pilot",
                "status": "complete",
                "total_accounts": 50,
                "migrated": 49,
                "failed": 1,
                "failed_accounts": [{"id": "acc-2001", "name": "test-oracle-01", "reason": "Password retrieval failed — account locked"}],
                "duration_minutes": 23,
                "batches": [
                    {
                        "batch_id": 1, "size": 50, "success": 49, "failed": 1,
                        "steps": [
                            {"step": "FREEZE", "status": "done", "duration_ms": 1200, "detail": "50 accounts frozen"},
                            {"step": "EXPORT", "status": "done", "duration_ms": 8500, "detail": "49 passwords retrieved, 1 failed"},
                            {"step": "TRANSFORM", "status": "done", "duration_ms": 450, "detail": "49 accounts transformed"},
                            {"step": "CREATE FOLDERS", "status": "done", "duration_ms": 2100, "detail": "3 folders created"},
                            {"step": "IMPORT", "status": "done", "duration_ms": 15600, "detail": "49 secrets created"},
                            {"step": "HEARTBEAT", "status": "done", "duration_ms": 45000, "detail": "48/49 heartbeat OK"},
                            {"step": "UNFREEZE", "status": "done", "duration_ms": 980, "detail": "50 accounts unfrozen"},
                        ],
                    }
                ],
            },
        },
        "pilot_validation": {
            "name": "Pilot Validation Report",
            "agent": "05",
            "format": "JSON",
            "data": {
                "overall_status": "PASSED",
                "success_rate": 0.98,
                "checks": [
                    {"name": "count_comparison", "passed": True, "detail": "49 source = 49 target (0.0% variance, 1 excluded)"},
                    {"name": "heartbeat_status", "passed": True, "detail": "48/49 verified (98.0%)"},
                    {"name": "permission_mapping", "passed": True, "detail": "0 permission exceptions"},
                    {"name": "folder_structure", "passed": True, "detail": "3 folders created, hierarchy correct"},
                    {"name": "metadata_integrity", "passed": True, "detail": "All description/custom fields preserved"},
                    {"name": "group_assignments", "passed": True, "detail": "12 group memberships translated"},
                    {"name": "password_policies", "passed": True, "detail": "Rotation policies applied per template"},
                    {"name": "access_patterns", "passed": True, "detail": "0 unexpected permission escalations"},
                    {"name": "audit_continuity", "passed": True, "detail": "Audit entries present for all 49 accounts"},
                    {"name": "recording_preservation", "passed": True, "detail": "N/A for pilot (manual verify in P7)"},
                ],
            },
        },
    },
    "p5": {
        "wave1_report": {
            "name": "Wave 1 Migration Report",
            "agent": "04",
            "format": "JSON",
            "data": {
                "wave": 1, "status": "complete",
                "total_accounts": 698, "migrated": 695, "failed": 3,
                "duration_minutes": 187,
                "batches": [
                    {"batch_id": 1, "size": 500, "success": 498, "failed": 2},
                    {"batch_id": 2, "size": 198, "success": 197, "failed": 1},
                ],
            },
        },
    },
}

# ── Comparison data ──────────────────────────────────────────────────

COMPARISON_ROWS = [
    {
        "category": "Authentication",
        "a": {"value": "OAuth2 client_credentials via /oauth2/token", "risk": "low"},
        "b": {"value": "ISPSS Identity OAuth2 via /oauth2/platformtoken", "risk": "low"},
    },
    {
        "category": "Permission Model",
        "a": {"value": "22 → 4 folder roles (LOSSY). 9 permissions have no SS equivalent. Escalation risk.", "risk": "high"},
        "b": {"value": "22 → 22 individual permissions (1:1 parity). Same Safe Members API.", "risk": "low"},
    },
    {
        "category": "Data Structure",
        "a": {"value": "Safe → Folder (hierarchical). Platform → Secret Template. Account → Secret.", "risk": "medium"},
        "b": {"value": "Safe → Safe. Platform → Platform. Account → Account. Same model.", "risk": "low"},
    },
    {
        "category": "Integration Path",
        "a": {"value": "Full re-architecture. Different auth (OAuth2), endpoints (/api/v1/), data format. Code regeneration required.", "risk": "high"},
        "b": {"value": "API URL change mostly. Same REST surface. Cert auth → ISPSS OAuth2 where needed.", "risk": "low"},
    },
    {
        "category": "Audit Retention",
        "a": {"value": "Manual export. CyberArk audit logs do NOT transfer to SS. Keep CyberArk read-only 1-7 years.", "risk": "high"},
        "b": {"value": "Audit logs migrate to Privilege Cloud. Continuous audit trail.", "risk": "low"},
    },
    {
        "category": "Session Management",
        "a": {"value": "StrongDM replaces PSM. Cedar policies, 100+ protocols, session recording.", "risk": "medium"},
        "b": {"value": "Cloud PSM. Same vendor, same session recording in cloud.", "risk": "low"},
    },
    {
        "category": "Connectors",
        "a": {"value": "Distributed Engine + RPC plugins (rebuild per template) + StrongDM Relay.", "risk": "medium"},
        "b": {"value": "Connector Server (MQTT TCP 443/8883). Cloud CPM manages rotation.", "risk": "low"},
    },
    {
        "category": "Password Rotation",
        "a": {"value": "RPC plugins + Distributed Engine. Must rebuild per Secret Template.", "risk": "medium"},
        "b": {"value": "Cloud CPM. Same CPM plugin architecture, cloud-managed.", "risk": "low"},
    },
    {
        "category": "PSM Recordings",
        "a": {"value": "Cannot migrate to SS. StrongDM replaces going forward. Archive CyberArk recordings.", "risk": "high"},
        "b": {"value": "Transfer to Privilege Cloud storage. Continuous availability.", "risk": "low"},
    },
    {
        "category": "Custom Platforms",
        "a": {"value": "Must create custom Secret Templates + RPC connection components.", "risk": "medium"},
        "b": {"value": "Built-in platform policies. Custom connection components via Connector.", "risk": "low"},
    },
]

PERMISSION_MAPPING = {
    "option_a": {
        "description": "22 CyberArk permissions → 4 Secret Server folder roles",
        "roles": [
            {
                "role": "Owner",
                "requires": "ManageSafe AND ManageSafeMembers",
                "cyberark_perms": ["ManageSafe", "ManageSafeMembers"],
            },
            {
                "role": "Edit",
                "requires": "ANY of: AddAccounts, UpdateAccountContent, UpdateAccountProperties, DeleteAccounts, RenameAccounts, UnlockAccounts",
                "cyberark_perms": ["AddAccounts", "UpdateAccountContent", "UpdateAccountProperties", "DeleteAccounts", "RenameAccounts", "UnlockAccounts"],
            },
            {
                "role": "View",
                "requires": "ANY of: UseAccounts, RetrieveAccounts",
                "cyberark_perms": ["UseAccounts", "RetrieveAccounts"],
            },
            {
                "role": "List",
                "requires": "ANY of: ListAccounts, ViewSafeMembers, ViewAuditLog",
                "cyberark_perms": ["ListAccounts", "ViewSafeMembers", "ViewAuditLog"],
            },
        ],
        "lost_permissions": [
            "AccessWithoutConfirmation", "SpecifyNextAccountContent", "BackupSafe",
            "CreateFolders", "DeleteFolders", "MoveAccountsAndFolders",
            "RequestsAuthorizationLevel1", "RequestsAuthorizationLevel2",
            "InitiateCPMAccountManagementOperations",
        ],
    },
    "option_b": {
        "description": "22 CyberArk permissions → 22 Privilege Cloud permissions (1:1 parity)",
        "note": "Same Safe Members API. All 22 permissions map directly.",
    },
}

PLATFORM_TEMPLATE_MAP = [
    {"cyberark": "WinServerLocal", "option_a": "Windows Account", "option_b": "WinServerLocal (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "WinDomain", "option_a": "Active Directory Account", "option_b": "WinDomain (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "UnixSSH", "option_a": "Unix Account (SSH)", "option_b": "UnixSSH (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "UnixSSHKeys", "option_a": "Unix Account (SSH Key Rotation)", "option_b": "UnixSSHKeys (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "Oracle", "option_a": "Oracle Account", "option_b": "Oracle (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "MSSql", "option_a": "SQL Server Account", "option_b": "MSSql (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "MySQL", "option_a": "MySQL Account", "option_b": "MySQL (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "AWSAccessKeys", "option_a": "Amazon IAM Key", "option_b": "AWSAccessKeys (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "AzureServicePrincipal", "option_a": "Azure Service Principal", "option_b": "AzureServicePrincipal (same)", "risk_a": "low", "risk_b": "low"},
    {"cyberark": "CustomWebApp", "option_a": "Custom template required", "option_b": "CustomWebApp (same)", "risk_a": "high", "risk_b": "low"},
    {"cyberark": "CiscoDevice", "option_a": "Custom template required", "option_b": "CiscoDevice (same)", "risk_a": "high", "risk_b": "low"},
]
