<#
.SYNOPSIS
    Secret Server Integration Module - PowerShell
    Converted from CyberArk CCP/psPAS
    Generated by PAM Migration Assistant

.DESCRIPTION
    Provides functions to retrieve secrets from Delinea Secret Server,
    replacing CyberArk CCP/AAM functionality.

.NOTES
    Requires: Thycotic.SecretServer PowerShell module
    Install: Install-Module -Name Thycotic.SecretServer -Scope CurrentUser

.EXAMPLE
    # Initialize session
    $session = Initialize-SecretServerSession

    # Get password
    $password = Get-SecretServerPassword -SecretId 1234

    # Get full credential
    $cred = Get-SecretServerCredential -SecretId 1234
#>

#Requires -Version 5.1

# Check for Thycotic.SecretServer module
if (-not (Get-Module -ListAvailable -Name Thycotic.SecretServer)) {
    Write-Warning "Thycotic.SecretServer module not installed."
    Write-Warning "Install with: Install-Module -Name Thycotic.SecretServer -Scope CurrentUser"
}

# Configuration - set via environment variables or modify here
$script:SSConfig = @{
    ServerUrl    = $env:SECRET_SERVER_URL ?? "https://secretserver.company.com/SecretServer"
    ClientId     = $env:SECRET_SERVER_CLIENT_ID
    ClientSecret = $env:SECRET_SERVER_CLIENT_SECRET
}

# Session management
$script:TssSession = $null

function Initialize-SecretServerSession {
    <#
    .SYNOPSIS
        Initialize connection to Secret Server

    .DESCRIPTION
        Creates and caches a Secret Server session using OAuth2 credentials.
        Reuses existing session if still valid.

    .OUTPUTS
        Thycotic.SecretServer.Session object

    .EXAMPLE
        $session = Initialize-SecretServerSession
    #>
    [CmdletBinding()]
    param()

    # Return existing session if valid
    if ($null -ne $script:TssSession -and $script:TssSession.IsValidToken()) {
        return $script:TssSession
    }

    # Validate configuration
    if ([string]::IsNullOrEmpty($script:SSConfig.ClientId)) {
        throw "SECRET_SERVER_CLIENT_ID environment variable not set"
    }
    if ([string]::IsNullOrEmpty($script:SSConfig.ClientSecret)) {
        throw "SECRET_SERVER_CLIENT_SECRET environment variable not set"
    }

    # Create credential from client ID/secret
    $secureSecret = ConvertTo-SecureString $script:SSConfig.ClientSecret -AsPlainText -Force
    $cred = New-Object System.Management.Automation.PSCredential(
        $script:SSConfig.ClientId,
        $secureSecret
    )

    # Create session
    $script:TssSession = New-TssSession -SecretServer $script:SSConfig.ServerUrl -Credential $cred

    return $script:TssSession
}

function Get-SecretServerPassword {
    <#
    .SYNOPSIS
        Retrieve password from Secret Server

    .DESCRIPTION
        Gets the password field value from a Secret Server secret.

        MIGRATION NOTE:
        CyberArk equivalent: Get-PASAccountPassword -AccountID <id>
        Response field: Password property

    .PARAMETER SecretId
        The Secret Server secret ID

    .OUTPUTS
        String - The password value

    .EXAMPLE
        $password = Get-SecretServerPassword -SecretId 1234
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [int]$SecretId
    )

    $session = Initialize-SecretServerSession
    $secret = Get-TssSecret -TssSession $session -Id $SecretId

    # Return password field
    return $secret.GetFieldValue("password")
}

function Get-SecretServerCredential {
    <#
    .SYNOPSIS
        Retrieve full credential (username + password) from Secret Server

    .DESCRIPTION
        Gets username and password from a secret and returns as PSCredential.

    .PARAMETER SecretId
        The Secret Server secret ID

    .OUTPUTS
        PSCredential object

    .EXAMPLE
        $cred = Get-SecretServerCredential -SecretId 1234
        Connect-Server -Credential $cred
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [int]$SecretId
    )

    $session = Initialize-SecretServerSession
    $secret = Get-TssSecret -TssSession $session -Id $SecretId

    $username = $secret.GetFieldValue("username")
    $password = $secret.GetFieldValue("password") | ConvertTo-SecureString -AsPlainText -Force

    return New-Object System.Management.Automation.PSCredential($username, $password)
}

function Get-SecretServerField {
    <#
    .SYNOPSIS
        Retrieve a specific field from a Secret Server secret

    .PARAMETER SecretId
        The Secret Server secret ID

    .PARAMETER FieldName
        The field name to retrieve (e.g., 'username', 'password', 'notes')

    .OUTPUTS
        String - The field value

    .EXAMPLE
        $notes = Get-SecretServerField -SecretId 1234 -FieldName 'notes'
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [int]$SecretId,

        [Parameter(Mandatory = $true)]
        [string]$FieldName
    )

    $session = Initialize-SecretServerSession
    $secret = Get-TssSecret -TssSession $session -Id $SecretId

    return $secret.GetFieldValue($FieldName)
}

function Search-SecretServerSecrets {
    <#
    .SYNOPSIS
        Search for secrets in Secret Server

    .PARAMETER SearchText
        Text to search for in secret names

    .PARAMETER FolderId
        Optional folder ID to limit search

    .OUTPUTS
        Array of secret summary objects

    .EXAMPLE
        $secrets = Search-SecretServerSecrets -SearchText "sql-admin"
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$SearchText,

        [Parameter()]
        [int]$FolderId
    )

    $session = Initialize-SecretServerSession

    $params = @{
        TssSession = $session
        SearchText = $SearchText
    }

    if ($FolderId) {
        $params.FolderId = $FolderId
    }

    return Search-TssSecret @params
}

function Test-SecretServerConnection {
    <#
    .SYNOPSIS
        Test connectivity to Secret Server

    .OUTPUTS
        Boolean - True if connection successful

    .EXAMPLE
        if (Test-SecretServerConnection) { Write-Host "Connected!" }
    #>
    [CmdletBinding()]
    param()

    try {
        $null = Initialize-SecretServerSession
        return $true
    }
    catch {
        Write-Warning "Secret Server connection failed: $_"
        return $false
    }
}

# Export functions
Export-ModuleMember -Function @(
    'Initialize-SecretServerSession',
    'Get-SecretServerPassword',
    'Get-SecretServerCredential',
    'Get-SecretServerField',
    'Search-SecretServerSecrets',
    'Test-SecretServerConnection'
)
