#!/usr/bin/env python3
"""
Secret Server Integration - Python Client
Converted from CyberArk CCP
Generated by PAM Migration Assistant

Usage:
    from secret_server_client import SecretServerClient

    client = SecretServerClient(
        base_url=os.environ.get("SECRET_SERVER_URL"),
        client_id=os.environ.get("SECRET_SERVER_CLIENT_ID"),
        client_secret=os.environ.get("SECRET_SERVER_CLIENT_SECRET")
    )

    password = client.get_password(secret_id=1234)
"""

import os
import time
import requests
from typing import Optional, List
from functools import lru_cache


class SecretServerClient:
    """Client for retrieving secrets from Delinea Secret Server."""

    def __init__(self, base_url: str, client_id: str, client_secret: str):
        """
        Initialize Secret Server client.

        Args:
            base_url: Secret Server URL (e.g., https://secretserver.company.com/SecretServer)
            client_id: OAuth2 client ID
            client_secret: OAuth2 client secret
        """
        self.base_url = base_url.rstrip('/')
        self.client_id = client_id
        self.client_secret = client_secret
        self._token = None
        self._token_expiry = 0

    def _get_token(self) -> str:
        """Get OAuth2 access token, refreshing if needed."""
        if self._token and time.time() < self._token_expiry - 60:
            return self._token

        response = requests.post(
            f"{self.base_url}/oauth2/token",
            data={
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret
            },
            timeout=30
        )
        response.raise_for_status()
        data = response.json()

        self._token = data["access_token"]
        self._token_expiry = time.time() + data.get("expires_in", 3600)
        return self._token

    def _headers(self) -> dict:
        """Get authorization headers."""
        return {"Authorization": f"Bearer {self._get_token()}"}

    def get_secret(self, secret_id: int) -> dict:
        """
        Retrieve a secret by ID.

        Args:
            secret_id: The Secret Server secret ID

        Returns:
            Full secret object with all fields
        """
        response = requests.get(
            f"{self.base_url}/api/v1/secrets/{secret_id}",
            headers=self._headers(),
            timeout=30
        )
        response.raise_for_status()
        return response.json()

    def get_password(self, secret_id: int) -> str:
        """
        Retrieve just the password field from a secret.

        Args:
            secret_id: The Secret Server secret ID

        Returns:
            Password string

        MIGRATION NOTE:
            CyberArk equivalent: GET /AIMWebService/api/Accounts?AppID=X&Safe=Y&Object=Z
            Response field: json["Content"]
        """
        response = requests.get(
            f"{self.base_url}/api/v1/secrets/{secret_id}/fields/password",
            headers=self._headers(),
            timeout=30
        )
        response.raise_for_status()
        return response.json()["value"]

    def get_field(self, secret_id: int, field_slug: str) -> str:
        """
        Retrieve a specific field from a secret.

        Args:
            secret_id: The Secret Server secret ID
            field_slug: Field name (e.g., 'username', 'password', 'notes')

        Returns:
            Field value as string
        """
        response = requests.get(
            f"{self.base_url}/api/v1/secrets/{secret_id}/fields/{field_slug}",
            headers=self._headers(),
            timeout=30
        )
        response.raise_for_status()
        return response.json()["value"]

    def search_secrets(
        self,
        search_text: str,
        folder_id: Optional[int] = None
    ) -> List[dict]:
        """
        Search for secrets by text.

        Args:
            search_text: Text to search for in secret names
            folder_id: Optional folder ID to limit search

        Returns:
            List of matching secrets (summary, not full details)
        """
        params = {"filter.searchText": search_text}
        if folder_id:
            params["filter.folderId"] = folder_id

        response = requests.get(
            f"{self.base_url}/api/v1/secrets",
            headers=self._headers(),
            params=params,
            timeout=30
        )
        response.raise_for_status()
        return response.json()["records"]

    def test_connection(self) -> bool:
        """Test connectivity to Secret Server."""
        try:
            self._get_token()
            return True
        except Exception:
            return False


# Convenience function for simple use cases
_default_client = None


def get_password(secret_id: int) -> str:
    """
    Convenience function to get password without managing client.

    Requires environment variables:
        SECRET_SERVER_URL
        SECRET_SERVER_CLIENT_ID
        SECRET_SERVER_CLIENT_SECRET

    Usage:
        from secret_server_client import get_password
        password = get_password(secret_id=1234)
    """
    global _default_client
    if _default_client is None:
        _default_client = SecretServerClient(
            base_url=os.environ.get("SECRET_SERVER_URL", ""),
            client_id=os.environ.get("SECRET_SERVER_CLIENT_ID", ""),
            client_secret=os.environ.get("SECRET_SERVER_CLIENT_SECRET", "")
        )
    return _default_client.get_password(secret_id)


if __name__ == "__main__":
    # Self-test
    print("Secret Server Client - Self Test")
    print("=" * 50)

    client = SecretServerClient(
        base_url=os.environ.get("SECRET_SERVER_URL", "https://localhost/SecretServer"),
        client_id=os.environ.get("SECRET_SERVER_CLIENT_ID", ""),
        client_secret=os.environ.get("SECRET_SERVER_CLIENT_SECRET", "")
    )

    if client.test_connection():
        print("Connection: SUCCESS")
    else:
        print("Connection: FAILED - Check environment variables")
